name: Full24TH Scraper

on:
  workflow_dispatch:

jobs:

  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python full24th-script.py

      - name: Commit Output
        run: |

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "auto update" || echo "no changes"

          git push
